name: PlayUHC
main: com.gmail.val59000mc.playuhc.PlayUhc
version: 1.9.4
description: Automates UHC games on a dedicated server
author: val59000mc, Mezy, Roman901
soft-depend: [WorldEdit]
api-version: 1.13
commands:
   playuhc:
        description: "Type '/playuhc help' to see a list of commands"
        usage: "/playuhc help"
        permission: "playuhc.commands"
        permissionMessage: "You don't have the permission to use PlayUHC commands"
   chat:
        description: "Type '/chat' to toggle global chat"
        usage: "/chat"
        aliases: [c]
        permissionMessage: "You don't have the permission to use PlayUHC commands"
   teleport:
        description: "Type '/teleport <player>' to teleport to your teammates while spectating"
        usage: "/teleport <player>"
        permissionMessage: "You don't have the permission to use PlayUHC commands"
        aliases: [tp]